app:
  ecr_uri: 313422618945.dkr.ecr.eu-central-1.amazonaws.com/devops-training-fabian/web-app
  image_tag: latest
  certificate_arn: arn:aws:acm:eu-central-1:313422618945:certificate/3cfb03c3-dc5c-4baa-a8bf-887b7f6f0878

  name: devops-training-fabian
  hostname: api.fabian.appstellar.training
  ingressClassName: alb
  port:
    servicePort: 80
    containerPort: 80
  requestCpu: 75m
  requestMem: 384Mi
  limitCpu: 90m
  limitMem: 500Mi
